### ISSUE TITLE
SASS Introduction

### ISSUE THREAD

**Issue by samirkarimov** [RRJafarov/distanceLearning#2]
#### Extentions
- Live Sass Compiler
- Sass

#### SASS Basics
- SASS Variables
- SASS Nesting
- SASS Partials
- SASS Modules
- SASS Mixins
- SASS Extend/Inheritance
- SASS Operators

#### Extra Reading
- [CSS Variables](https://www.w3schools.com/css/css3_variables.asp)

#### SASS Best Parts
- Sürətli kod yazmaqda
- Yenilə bilən kod yazmaqda
- Sistemli kod yazmaqda
- Planlı kod yazmaqda
- Komanda şəklində işlədiyimiz zaman

#### Task

- [ ]  VSCode-da SASS və Live SASS Compiler extentionlarını yüklə
- [ ] Dərsdə izah edildiyi kimi SASS konfiqurasiyasını reallaşdır
- [ ] Aşağıdakı suallar haqqında araşdırma edərək comment hissəsində nömrəli şəkildə cavablandır.Suallara cavab yazarkən maksimum şəkildə ətraflı yazmağa çalış ki mövzuya yanaşma tərzin tam aydın olsun.

1. Sənə görə CSS yazarkən bizim sürətli yazmağımıza mane olacaq şeylər nələrdir?
2. CSS yazarkən `Kaş bu aftomatlaşdırılmış olsaydı` deyə biləcəyin məqamlar hansılardır?
3. SASS variable məntiqini layihədə harda istifadə edə bilərsən?

#### Qeydlər
- [SASS Introduction Dərs Videosu](https://vimeo.com/719784568)  | Password :!mjGGN7gU7cJG`<}
- Tapşırıqlarla və mövzu ilə bağlı suallarını comment hissəsində bildir
- Tapşırıqları bitirdikdən sonra `@samirkarimov` formatında müəllimi etiketləyərək məlumat ver

**Comment by samirkarimov** [comment]
@RRJafarov dərs tapşırığını nə zaman təhvil vərəcəyini qeyd et zəhmət olmasa

**Comment by samirkarimov** [comment]
@RRJafarov ...

**Comment by samirkarimov** [comment]
Yeni dersi gonderirem Rafael.Bu arada Hebible senin derslerinle bagli meseleleri yoluna qoyduq qismen.Sen disttanda davam edeceksen. men sene grafik cixaracam iyul ayindan heftenin 3 gunu ofisde gelib mesqul olacaqsan bizim nezaretimizde
